theme: jekyll-theme-cayman
title: [Bots war: cyber attacks]
description: [One way of detecting cyber attacks is through the collection of all the pertinent information that allows us to perform optimized searches for the timely detection of malicious access through robot networks.]
show_downloads: ["true"]
